### PR TITLE
Minor Fix: code quality gocardless_settings.json

### PR DESCRIPTION
**Pull request by trustedcomputer**
Update field_order and updated date/time stamp in gocardless_settings.json
This was not done in https://github.com/frappe/payments/pull/66

### CODE REVIEW

**Comment by NagariaHussain** [comment]
This does not look complete, the field json is missing 🤔

**Comment by trustedcomputer** [comment]
Hi @NagariaHussain, If I'm understanding your comment correctly, I added the header_img field to the JSON in https://github.com/frappe/payments/pull/66

But in that PR I neglected to add that new field, to the field_order section of the JSON file. So this PR is just fixing that mistake I made in the already merged PR. Did I mis-understand your comment or does that clear it up?

**Comment by NagariaHussain** [comment]
You are manually editing JSON?

**Comment by trustedcomputer** [comment]
Yes, JSON is where the fix is needed.

**Pull request closed without merging**
